\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{cs161}[2022/01/14 v1.0 by Nicholas Ngai]

\LoadClass{exam}

\makeatletter

% Course number, course name, instructor, term.
\newcommand{\courseno@ucbcs}{}
\newcommand{\coursename@ucbcs}{}
\newcommand{\courseterm@ucbcs}{}
\newcommand{\courseinstructor@ucbcs}{}
\newcommand{\courseno}{\renewcommand{\courseno@ucbcs}}
\newcommand{\coursename}{\renewcommand{\coursename@ucbcs}}
\newcommand{\courseterm}{\renewcommand{\courseterm@ucbcs}}
\newcommand{\courseinstructor}{\renewcommand{\courseinstructor@ucbcs}}

\makeatother
